package com.denemeler.harfsayar;

import java.util.ArrayList;
import java.util.List;

public class Iller {
    private List<String> iller;
    public Iller() {
        iller = new ArrayList<>();
        iller.add("Adana");
        iller.add("Adıyaman");
        iller.add("Afyonkarahisar");
        iller.add("Ağrı");
        iller.add("Amasya");
        iller.add("Ankara");
        iller.add("Antalya");
        iller.add("Artvin");
        iller.add("Aydın");
        iller.add("Balıkesir");
        iller.add("Bilecik");
        iller.add("Bingöl");
        iller.add("Bitlis");
        iller.add("Bolu");
        iller.add("Burdur");
        iller.add("Bursa");
        iller.add("Çanakkale");
        iller.add("Çankırı");
        iller.add("Çorum");
        iller.add("Denizli");
        iller.add("Diyarbakır");
        iller.add("Edirne");
        iller.add("Elazığ");
        iller.add("Erzincan");
        iller.add("Erzurum");
        iller.add("Eskişehir");
        iller.add("Gaziantep");
        iller.add("Giresun");
        iller.add("Gümüşhane");
        iller.add("Hakkari");
        iller.add("Hatay");
        iller.add("Isparta");
        iller.add("Mersin");
        iller.add("İstanbul");
        iller.add("İzmir");
        iller.add("Kars");
        iller.add("Kastamonu");
        iller.add("Kayseri");
        iller.add("Kırklareli");
        iller.add("Kırşehir");
        iller.add("Kocaeli");
        iller.add("Konya");
        iller.add("Kütahya");
        iller.add("Malatya");
        iller.add("Manisa");
        iller.add("Kahramanmaraş");
        iller.add("Mardin");
        iller.add("Muğla");
        iller.add("Muş");
        iller.add("Nevşehir");
        iller.add("Niğde");
        iller.add("Ordu");
        iller.add("Rize");
        iller.add("Sakarya");
        iller.add("Samsun");
        iller.add("Siirt");
        iller.add("Sinop");
        iller.add("Sivas");
        iller.add("Tekirdağ");
        iller.add("Tokat");
        iller.add("Trabzon");
        iller.add("Tunceli");
        iller.add("Şanlıurfa");
        iller.add("Uşak");
        iller.add("Van");
        iller.add("Yozgat");
        iller.add("Zonguldak");
        iller.add("Aksaray");
        iller.add("Bayburt");
        iller.add("Karaman");
        iller.add("Kırıkkale");
        iller.add("Batman");
        iller.add("Şırnak");
        iller.add("Bartın");
        iller.add("Ardahan");
        iller.add("Iğdır");
        iller.add("Yalova");
        iller.add("Karabük");
        iller.add("Kilis");
        iller.add("Osmaniye");
        iller.add("Düzce");
    }
    public List<String> getIller() {
        return iller;
    }
}